basePath: /api
definitions:
  api.errorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
  models.Product:
    properties:
      id:
        example: 1
        type: integer
      properties:
        additionalProperties:
          type: string
        example:
          '{"штрихкод"': '"12345678"}'
        type: object
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис товаров.
  title: MarketService API
  version: "1.0"
paths:
  /products/get:
    get:
      consumes:
      - application/json
      description: get a list of product with pagination and sorting
      operationId: getProducts
      parameters:
      - description: Page number (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of items per page (default is 2)
        in: query
        name: limit
        type: integer
      - description: Sorting order (default is 'asc')
        in: query
        name: sortOrder
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of product
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: get list of product
      tags:
      - Products
swagger: "2.0"
